-- MySQL Script generated by MySQL Workbench
-- Sat Dec 18 18:56:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema baitap1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baitap1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baitap1` ;
USE `baitap1` ;

-- -----------------------------------------------------
-- Table `baitap1`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baitap1`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `rank` TINYINT(4) NULL,
  `is_active` TINYINT(1) NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baitap1`.`caterogy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baitap1`.`caterogy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baitap1`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baitap1`.`blog` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `view` INT(11) NULL,
  `is_active` TINYINT(1) NULL,
  `content` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `user_id` INT(11) NOT NULL,
  `caterogy_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_blog_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_blog_caterogy1_idx` (`caterogy_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `baitap1`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blog_caterogy1`
    FOREIGN KEY (`caterogy_id`)
    REFERENCES `baitap1`.`caterogy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baitap1`.`follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baitap1`.`follow` (
  `id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `from_user_id` INT(11) NOT NULL,
  `to_user_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_follow_user2_idx` (`from_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_follow_user2`
    FOREIGN KEY (`from_user_id`)
    REFERENCES `baitap1`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baitap1`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baitap1`.`comment` (
  `id` INT(11) NOT NULL,
  `target_table` VARCHAR(20) NULL,
  `target_id` INT(11) NULL,
  `comment` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `baitap1`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baitap1`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baitap1`.`news` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `view` INT(11) NULL,
  `is_active` TINYINT(1) NULL,
  `content` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `caterogy_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_news_caterogy1_idx` (`caterogy_id` ASC) VISIBLE,
  CONSTRAINT `fk_news_caterogy1`
    FOREIGN KEY (`caterogy_id`)
    REFERENCES `baitap1`.`caterogy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
